apiVersion: v1
kind: Pod
metadata:
  name: test-mdt-config-skip-uncertainties
spec:
  containers:
  - name: test-mdt-config-skip-uncertainties
    image: mrigroupopbg/mri-mdt:latest
    command: ["bash", "-c", "/app/run.sh"]
    volumeMounts:
    - name: mdt-config
      mountPath: /root/.mdt/1.2.2/mdt.conf
      subPath: mdt.conf
    - name: data-rmn
      mountPath: /data/RMN
    - name: script
      mountPath: /app/run.sh
    resources:
      limits:
        nvidia.com/gpu: 1
  restartPolicy: Never
  volumes:
  - name: data-rmn
    hostPath:
      path: /data/RMN
  - name: mdt-config
    configMap:
      name: mdt-config-skip-uncertainties
  - name: script
    hostPath:
        path: /data/RMN/LAURA_BRESCHI/prova_MDT_docker.sh


